### ISSUE TITLE
Calling Post in parallel in large number of threads cause double free exception

### ISSUE THREAD

**Issue by rahulbhalerao001** [whoshuu/cpr#101]
This is the error when executing Posts in parallel.

double free or corruption (!prev): 0x00000000018ce630 ***
Aborted (core dumped)

Any suggestions to solve such an error will be very helpful.

**Comment by whoshuu** [comment]
Interesting, it might be an issue with curl itself. Linking this page here for future reference before formulating a strategy for resolving this: https://curl.haxx.se/libcurl/c/threadsafe.html.

The relevant text is probably here:

>curl_global_* functions
These functions are not thread safe. If you are using libcurl with multiple threads it is especially important that before use you call curl_global_init or curl_global_init_mem to explicitly initialize the library and its dependents, rather than rely on the "lazy" fail-safe initialization that takes place the first time curl_easy_init is called. For an in-depth explanation refer to libcurl section GLOBAL CONSTANTS.

**Comment by rahulbhalerao001** [comment]
Hello @whoshuu ,

Thank you for your reply.

I feel the issue for my crash was a multithreading issue in the open ssl and thus the curl module.
Openssl recommends setting up 2 callbacks when using their code in multithreading. So I used the 2 callbacks from http://stackoverflow.com/a/27567259, and that solved my issue.
