### ISSUE TITLE
how does merge cookie

### ISSUE THREAD

**Issue by charlessoft** [whoshuu/cpr#102]
have two cpr::Session , so have two different cookies, how does merge the cookies?

**Comment by charlessoft** [comment]
how does traversal the cpr::Cookie

**Comment by whoshuu** [comment]
Currently there isn't a way to merge or traverse the cookies without modifying source code. If you want, you can change the private `map_` [here](https://github.com/whoshuu/cpr/blob/3fc28f0ea332a0423474be9077e91f4146d83661/include/cpr/cookies.h#L21) to be public and iterate through it through the usual means since it's just a `.std::map`.

**Comment by COM8** [comment]
I'm closing this, since it seems to be fixed by #365.
Feel free to reopen this, when needed.
