### ISSUE TITLE
Does CPR support keep-alive with HTTP1.1 ?

### ISSUE THREAD

**Issue by pengweichu** [whoshuu/cpr#193]
Does CPR support keep-alive with HTTP1.1(if the server already support) ? If support, where can I setup it ?

Since I don't want to create a new TCP connection when make every POST request.

Thanks

**Comment by mbumba** [comment]
Hello pengweichu, I thing you can create new cpr:Session, which using keep alive and then call HTTP request acros this session (e.q. https://github.com/whoshuu/cpr/blob/master/test/session_tests.cpp#L698 ).

**Comment by pengweichu** [comment]
@mbumba thanks for your help, does the session supports async request ? I have checked the session_tests.cpp, don't see any async method to send request.

**Comment by TheAssassin** [comment]
@mbumba how sure are you about the support for `keep-alive`? It doesn't seem like a session persists the TCP connection, it only makes sure an existing connection will be [kept alive](https://github.com/whoshuu/cpr/blob/master/cpr/session.cpp#L78). Probably have to write a test program for this with `CURLOPT_VERBOSE=1` in my environment.

**Comment by TheAssassin** [comment]
I can answer my own question:

First of all, HTTP 1.1 is keep-alive by default as per the specification, in opposite to HTTP 1.0 where it had to be enabled using `Connection: keep-alive` headers.

Turns out cURL supports it out of the box. When reusing the same curl handle (doesn't matter whether easy or multi handle), some TCP connections are stored for re-use. See also https://ec.haxx.se/usingcurl-persist.html.

As a session appears to hold a [single handle](https://github.com/whoshuu/cpr/blob/master/cpr/session.cpp#L61) during its existence, therefore cURL's persistent connection feature can work as intended.
