### ISSUE TITLE
PostCallback seems block UI thread in iOS

### ISSUE THREAD

**Issue by mmohiahmed** [whoshuu/cpr#199]
Hi! I am using  cpr::PostCallback (see code bellow) in iOS. It seems   cpr::PostCallback is blocking the UI thread untill http response comes back. Any comment would be much appreciated.
Thanks !

 auto mapDataParser = [this](cpr::Response r)->void{
        LOGD_IF(PRINT_DLOG) << AGCMapKitUtil::timeStamp() << "*********** HTTP_BACK ************\n\n";
        return;
    };
    LOGD_IF(PRINT_DLOG) << AGCMapKitUtil::timeStamp() << "*********** HTTP_1 ************";
    auto future_text = cpr::PostCallback(mapDataParser, cpr::Url{msUrl}, cpr::Body{szBuffer});
    LOGD_IF(PRINT_DLOG) << AGCMapKitUtil::timeStamp() << "*********** HTTP_2 ************";

1495086046405*********** HTTP_1 ************
1495086046405*********** HTTP_2 ************
1495086047716*********** HTTP_BACK ************  [UI thread stuck here for 1.3s ]

**Comment by Taymindis** [comment]
You can use backcurl >> https://github.com/Taymindis/backcurl, it is appropriate for Mobile

**Comment by Taymindis** [comment]
You can try nonblockpp >> https://github.com/Taymindis/NonBlockpp , you can do background task and runOnMainthread
```cpp
int partialUpdate=0;
NonBlk::run([](int &updating) {
   // Doing HTTP Calling
   // ....
   // Done 
    NonBlk::runOnMainThread([]() {
        std::cout << "Success call with same thread id " << mainThreadId << " ==  " << std::this_thread::get_id() << "\n";
    });
}, std::ref(partialUpdate));
```

**Comment by iPherian** [comment]
@mmohiahmed Rest assured, when used properly the *Callback functions are asynchronous. You see, discarding the future from `postCallback` too early may cause it to block. 

If the lag occurs at the end of the scope where you declared `auto future_text`, this is probably the answer. Try keeping the future around (somewhere else) until the http request completes.

The reason why this occurs is because `postCallback` uses `std::async`:

>If the std::future obtained from std::async is not moved from or bound to a reference, the destructor of the std::future will block at the end of the full expression until the asynchronous operation completes.

http://en.cppreference.com/w/cpp/thread/async
