### ISSUE TITLE
build as a submodule is complicated

### ISSUE THREAD

**Issue by yoni386** [whoshuu/cpr#215]
cloning the repro https://github.com/whoshuu/cpr-example is working and using the global curl.

why mongoose is included? can you make the fork thin and maybe add more info how include it without clone the full repo https://github.com/whoshuu/cpr-example
More info how use the global curl (cmake guild).

**Comment by whoshuu** [comment]
The fork is already thin, you don't need to sync every git submodule. The instructions for building this library with tests include a command to sync all submodules, but you can just as easily just do `git submodule update --init opt/curl` to update just curl, for instance.

As for a **distribution** that's thin, that's definitely a goal. I would love to be able to install the headers and libs from this project with `apt` or `brew`.

Otherwise, unless there are other specific requests or issues, I'll mark this ticket for closing. Let me know if you want me to keep it up though.

**Comment by yoni386** [comment]
Thanks
