### ISSUE TITLE
does this project still live ?

### ISSUE THREAD

**Issue by pengweichu** [whoshuu/cpr#290]
does this project still live ?

**Comment by deblauwetom** [comment]
I think with 27 open pull requests, it's safe to say that the original author has lost interest it seems :p

**Comment by ivanivkovic** [comment]
Such a pitty

**Comment by deblauwetom** [comment]
@whoshuu : what is the state now? There are some useful pull requests that really should get commited.

**Comment by tstack** [comment]
@whoshuu If you're not going to maintain it, would you be willing to transfer ownership to someone else?

**Comment by tstack** [comment]
@whoshuu I'm willing to take ownership if you don't have someone else in mind.  If you need some evidence that I'm not a bozo, I've developed/maintained https://github.com/tstack/lnav for over a decade.  This project is pretty popular and a transfer would make it easier to keep going rather than doing a fork.

**Comment by daquexian** [comment]
@whoshuu It is an excellent project and worthwhile to be maintained. If you do not have enough time I believe transferring it to someone (e.g., @tstack ) is a good idea

**Comment by amrox** [comment]
@whoshuu second the transfer to @tstack if you'd rather not maintain it yourself

**Comment by deblauwetom** [comment]
If you look at the history of his activity: there seems to be some even in august... so he seems to be still online on github, but is really ignoring this thread and question... my conclusion would be that tstack can make a fork and we can work on that repo instead, and that way we can all move forward!

**Comment by tstack** [comment]
A fork would be fine, but there's quite a lot of Pull Requests and Issues attached to this repo that we'd lose track of.  A transfer would be nicer overall.  @whoshuu, would you prefer a separate github org be setup and transfer the repo into there so that it's not bound to an individual?  Please respond.

**Comment by whoshuu** [comment]
Closing this issue as @tstack is now the maintainer of the project :beers:
