### ISSUE TITLE
curses.h can break cpr/error.h

### ISSUE THREAD

**Issue by sessionm21** [whoshuu/cpr#317]
Including curses.h before cpr/cpr.h will cause the build to fail in errro.h
``` bash
/<redacted>/src/cpr/include/cpr/error.h:13:5: error: expected identifier before ‘(’ token
     OK = 0,
     ^~
```
Fedora release 29 (Twenty Nine)
``` bash
g++ (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ssnover95** [comment]
The problem is that curses.h uses a macro to define the symbol `OK` which does not play well with C++ enums since it ignores scoping and namespaces. If you aren't using the enum member in your actual source, you can fix your build by reordering or with compiler pragmas.
For GCC:
```
#include <curses.h>
#pragma push_macro("OK")
#include <cpr/cpr.h>
#pragma pop_macro("OK")
```

Just know that if you do decide to use that enum member in your code you'll get a pretty nondescript error that's hard to debug. You could try undefining the macro all together and making an adapter header which defines a C++ enum with the values of the `OK` macro and the related macro constants.

**Comment by COM8** [comment]
Feel free to reopen this issue, if the answer from @ssnover95 did not resolve your problem.
