### ISSUE TITLE
Is project alive? - TLDR: Yes

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [whoshuu/cpr#362]
Hi!
I am not sure - is this project alive or not?

**Comment by RazdolbayOne** [comment]
Well I assume it is in zombie stage.

**Comment by xloem** [comment]
Although most activity is from years ago, there are some commits from only a few months ago here.

It would be nice for such an essential library to have more active closing and addressing of issues and pull requests.  It's been years now since the goals of streaming and SSL support were added.

Maybe the authors of the PRs and forks could be possible people to reach out to if more work-hours were needed maintaining the repository.  If @whoshuu disappears or has disappeared we could collect people around one of the forks.

**Comment by tstack** [comment]
Sorry, been overloaded with work and life.  I will have some time off soon (and nowhere to go), so I'll get back to working on it.  If anyone is interested in contributing, I can grant some privileges.

**Comment by COM8** [comment]
@tstack A couple of days I wrote you a mail regarding this topic.
I think it landed in your spam folder since I was writing it from my spoofed university mail account.
Gmail is quite strict about that.

**In a nutshell:**  
@kingkili and I (@COM8) would be able to either take over the project as maintainers or as your co maintainers and work on open PRs and issues.

**Comment by ZaMaZaN4iK** [comment]
@tstack can you grant to other people contribute permissions to the repository? It will help a lot in maintaining such library.

Thank you a lot!

@COM8 and @KingKili - thanks a lot. Possibly other people also is interested in maintaining/co-maintaining - it will be wonderful. Can you write another emails to the @tstack please? I think together we can make `cpr` great again :)

**Comment by COM8** [comment]
> @tstack can you grant to other people contribute permissions to the repository? It will help a lot in maintaining such library.
> 
> Thank you a lot!
> 
> @COM8 and @KingKili - thanks a lot. Possibly other people also is interested in maintaining/co-maintaining - it will be wonderful. Can you write another emails to the @tstack please? I think together we can make `cpr` great again :)

Done.

**Comment by tstack** [comment]
Unfortunately, I don't seem to have the access needed to add maintainers (no Settings tab up top).  I can only seem to merge pull requests.

**Comment by COM8** [comment]
> Unfortunately, I don't seem to have the access needed to add maintainers (no Settings tab up top). I can only seem to merge pull requests.

Are you able to get in contact with the original maintainer (@whoshuu ) for this some how?

**Comment by tstack** [comment]
> Are you able to get in contact with the original maintainer (@whoshuu ) for this some how?

I sent an email, we'll see.

In the meantime, doing reviews of the open pull requests would be helpful.  After this week, I will be off for a couple weeks and will focus down and do more reviews/merges.  I'll cut a release at the end of next week.

**Comment by KingKili** [comment]
@tstack can you please add me too.

**Comment by xloem** [comment]
If whosuu doesn't respond it would make sense to fork the repository.

**Comment by ZaMaZaN4iK** [comment]
@xloem the biggest problem with forking is that all potential users shall know, which version is actual. It's very difficult to do, trust me. So I suggest forking iff original author doesn't respond during several weeks.

If he/she/it will no respond - I think in this issue we can collaborate together, discuss, choose proper place to fork, prepare a pull request to this repo, which will inform, that future development will be continued in another repo, etc.

So for now we can just wait :)

**Comment by whoshuu** [comment]
Hey all, we're actually in the process of migrating the project over to an organization on GitHub so that we can implement a more proper maintainer/contributor structure. As it stands, since this is a personal project, I can only invite collaborators onto the project, and those collaborators have no means of delegating subtasks or others, unless they are also explicitly invited by me.

Currently putting together a plan with Tim for this migration, which will incur an initial confusion period as the namespace of the project would live in the organization instead of my personal namespace. After that, we'll have admins, maintainers, and contributors.

I understand the demand for contributing to this project far exceeds the supply, albeit unnaturally. The hope is that this will alleviate that.

**Comment by eugenwintersberger** [comment]
I would like to use the code in several company projects and thus would like to contribute to the project. What is the current status of the migration to the new organization?

**Comment by COM8** [comment]
> I would like to use the code in several company projects and thus would like to contribute to the project. What is the current status of the migration to the new organization?

Nothing so far.
Have not heard back from @tstack or @whoshuu about this.
Feel free to create PRs and I will try merge them until we have an organisation.

**Comment by xloem** [comment]
First person to make an organization gets my follow and star!  =)  can always make the old maintainers maintainers of a new one made by someone else.
