### ISSUE TITLE
How to use with Android ndk?

### ISSUE THREAD

**Issue by Futuremappermydud** [whoshuu/cpr#388]
I need a shared library(.so) and the header files that i can include in my android c++ project how would i do this

**Comment by COM8** [comment]
Ping @kingkili.

**Comment by KingKili** [comment]
I must be honest, I have never worked with android. But if you want to get the headers and .so file I would do it like this:
``
git clone https://github.com/whoshuu/cpr.git
mkdir cpr/build
cd cpr/build
cmake .. -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=out
cmake --build . --target install
``
The required files should be afterwards in the folder out. But I am sceptical if this helps, since it will be a build for your current OS.

**Comment by COM8** [comment]
Closing this, since one month of inactivity.
Feel free to reopen in case this is still a problem.
