### ISSUE TITLE
Connection Pooling

### ISSUE THREAD

**Issue by LukeMauldin** [whoshuu/cpr#448]
Is there any way to configure CPR to take advantage of the underlying libcurl functionality to share connections between http requests to the same IP:Port?

**Comment by COM8** [comment]
Yes, and no.
You are able to *reuse* a connection if you use a `cpr::Session` object ([Docs](https://whoshuu.github.io/cpr/advanced-usage.html#session-objects)).

An actual connection pool does not exist. A while back there existed a PR (#330) for thread shared connection pools.
But this PR has never been merged since it lacked a couple of things.
