### ISSUE TITLE
Windows Builds not usable

### ISSUE THREAD

**Issue by COM8** [whoshuu/cpr#520]
Currently there are a lot of issues related to Windows builds with OpenSSL, as well as with WINSSL.
HTTPS requests just dont work and creating a static lib is also broken.
Related issues:
* #509
* #498
* #438
* #361

Besides that linking in vcpkg is also more or less broken.

**Comment by COM8** [comment]
Has anybody here knowledge about how fix our CMake for Windows?

**Comment by acidicoala** [comment]
Regarding static builds: the issue goes beyond cpr, it's the libcurl's fault. It always had issues with linking to some of the static libraries on Windows.

A simple workaround would be to manually link the required libraries via following definitions, which can be defined anywhere:
```c
#pragma comment(lib,"Ws2_32.lib")
#pragma comment(lib,"Wldap32.lib")
#pragma comment(lib,"Crypt32.lib")
```
Alternatively, if using MSVC, they can be added to Project Properties -> Linker -> Input -> Additional Dependencies.

**Comment by anticrisis** [comment]
It's probably no help to you, but I'm not having trouble on Windows, using vcpkg in a cmake project with Visual Studio. The test from https://github.com/whoshuu/cpr/issues/509 works fine for me. I created a test executable inside a small hobby project I'm working on. It uses vcpkg's `vcpkg.json` file to automatically install dependencies. Here are the relevant files in case the differences help you find out what is not working in your environment.

`vcpkg.json`:
```json
{
  "name": "sagr",
  "version-string": "0.1.0-dev",
  "dependencies": [
    "sqlite3",
    "boost-beast",
    "boost-json",
    "cpr",
    "fmt"
  ]
}
```

```cmake
# project root CMakeLists.txt
cmake_minimum_required(VERSION 3.19)

#
# Find VCPKG toolchain file via env variable if needed.
#
if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      CACHE STRING "")
endif()

project(sagr_project
  VERSION "0.1.0"
  DESCRIPTION "sagr"
  LANGUAGES CXX)

# Set these globally for all targets in this project
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED YES)
set(CMAKE_CXX_EXTENSIONS OFF)

if(MSVC)
    add_compile_definitions(WINVER=0x0A00 _WIN32_WINNT=0x0A00)
endif()


add_subdirectory(test/test_cpr)
```


```cmake
# test/test_cpr/CMakeLists.txt
cmake_minimum_required(VERSION 3.19)

add_executable(test_cpr main.cpp)

find_package(cpr CONFIG REQUIRED)
target_link_libraries(test_cpr PRIVATE cpr)
```

```cpp
// test/test_cpr/main.cpp
#include <cpr/cpr.h>
#include <iostream>

int
main()
{
  cpr::Response resp = cpr::Get(cpr::Url{ "https://httpbin.org/get" });

  std::cout << resp.text << std::endl;
  return 0;
}

```

**Comment by c0nd3v** [comment]
So, I think the reason that HTTPS is not working on Windows is because currently we don't have a way to load the root certificates.

**Comment by c0nd3v** [comment]
So, I think the reason that HTTPS is not working on Windows is because currently we don't have a way to load the root certificates.

On WinSSL, it should be able to load the root certificates from the certificate store.
The vcpkg version of cpr uses WinSSL by default as far as I'm aware (Thats why https works when using vcpkg, but doesnt work for non-vcpkg projects)

If you're using OpenSSL, by default it will not load the root certificates from the certificate store.
You have two options:

1, Add this curl option:
```cs
curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);
```
(Source: https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html#CURLSSLOPTNATIVECA)

2. Use `CURLOPT_SSL_CTX_FUNCTION` (Source: https://curl.se/mail/meet-2017-03/0030.html)

And if you're like me, and using mbedTLS, you can do this:
https://curl.se/mail/lib-2019-06/0057.html
https://www.mail-archive.com/curl-library@cool.haxx.se/msg29399.html

I hope this helps the project maintainers, or someone else having problems using HTTPS. Its really a pain to get working.

**Comment by COM8** [comment]
Can somebody test #529. This should fix a lot of issues related to Windows and (Open)SSL.

**Comment by COM8** [comment]
Closing this since [cpr v1.6.0](https://github.com/whoshuu/cpr/releases/tag/1.6.0) has been released including a bunch of fixes for Windows and SSL in general.
