### ISSUE TITLE
What does "CPR" stand for?

### ISSUE THREAD

**Issue by pctopgs** [whoshuu/cpr#527]
Is it "C++ Requests": C Plusplus Requests?
 How it is currently pronounced? "C-P-R"?

Can we change it CPPR: C Plus Plus Requests, and pronounce it "Copper"?

**Comment by COM8** [comment]
CPR stands for "C++ Requests" and it's pronounced "C-P-R", so you are right :)

I like your suggestion there. Sounds definitely cool!
But I'd say for sake of simplicity we should keep it as CPR since otherwise I fear there is a lot of work required to change this (namespace, website, git repo, ...).
