### ISSUE TITLE
Usage question for reducing response time with multiple requests

### ISSUE THREAD

**Issue by Meldryt** [whoshuu/cpr#552]
Whats the fastest approach to perform multiple requests sequentially or parallel with cpr?
I tried `cpr::Response r = cpr::Get()` but i have response times up to > 1 second which is too long for my use case.
Should i use session object instead? What about the ssl options? Or should i use libcurl instead ?

**Comment by COM8** [comment]
Using `cpr::Session` is the way to go here, since it keeps the underlying SSL/TLS connection up.
In case you use cpr from multiple threads, ensure every thread has its own session object, since cpr is **not** thread save on it's own.

cpr acts as a wrapper around libcurl.
If you want to set some specific options which are not (yet) provided by cpr you can access the curl object directly.
https://whoshuu.github.io/cpr/advanced-usage.html#session-objects
(at the end of this chapter is an example for that)

**Comment by Meldryt** [comment]
@COM8 Thanks. I read the guide. Its really helpful. 
I tried multiple threads and it worked out of the box, reduced my average request/response time a lot :) 
Also switched to cpr::Session, but couldn't see much of a difference. Maybe there is not much room a improvement when you use a different url for each request.

**Comment by COM8** [comment]
Glad to hear :)
