### ISSUE TITLE
Distro Packages (Particularly AUR)

### ISSUE THREAD

**Issue by ZLima12** [whoshuu/cpr#555]
I really like this library, but I don't like using CMake, so [I made an AUR package for it](https://aur.archlinux.org/packages/cpr/). I think others might be in the same boat, so I wonder if having packages for other distros would be beneficial.

Either way, I'm not sure if this one package is significant enough to put in the readme, but I just wanted to let people know about this here.

**Comment by COM8** [comment]
In case it is actively maintained, yes, sure, would love to!
Else, I prefer not to add it to the README.md, since people tend to expect stuff to be maintained and where do the come to when it is not working?
Yes, right! They create an issue here for it, just to get disappointed I/we can't help them (like for the vcpkg stuff...).

So if you/somebody else can confirm to me, you/they are maintaining it actively, go ahead and create a PR for it!

**Comment by ZLima12** [comment]
I'll be actively maintaining this AUR package, yes. I'll make a PR for it later today.
