### ISSUE TITLE
Cookies should not be URL encoded

### ISSUE THREAD

**Issue by arkbriar** [whoshuu/cpr#89]
I got weird errors when using CPR as the network module of my project. 
And after reading the code, I found the cookies encoded in Session::Impl::SetCookies(). 
However, RFC 6265 does not require cookies to be URL encoded.
Here is the [RFC 6265 Section 5.4](http://tools.ietf.org/html/rfc6265#section-5.4).

**Comment by whoshuu** [comment]
Hey @ArkBriar, thanks for bringing up the issue. Looks like I originally url encoded the cookies because that's de facto how many user agents send cookies, but the RFC you linked says that needn't be the case.

It makes sense to always send raw cookies, and if the client needs cookies to be url encoded, they can do it themselves by including the utility header.

**Comment by bhansen-uber** [comment]
Similarly, other header values should not be URL encoded in parameters.cpp.  https://tools.ietf.org/html/rfc2616#section-4.2 says that the token-content can be *TEXT, which is <any OCTET except CTLs, but including LWS>.

cpr is encoding some our headers that have embedded = signs, so we can't use it.

**Comment by boxmein** [comment]
I'd like to bring this up again with a different context. 

I'm authenticating to a cookie based API, and saving the received cpr::Cookies object to pass it on with future requests.

However, the cookie looks like:

    session=s:XYZWXYZW:yzzywzzwzxy

The : are encoded by the server, and the encoded value is saved into cpr::Cookies.

When re-sending the same Cookies object, they get encoded again, and the following data is sent instead:

    session=s%253AXYZWXYZW

It's clearly double encoding the string.

**Comment by COM8** [comment]
This has been fixed by #370 .
